name: Release module version

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    uses: urob/zmk-actions/.github/workflows/upgrade-module.yml@21d0254c00fa8e85b20089df82dc5e96d5029bd4 # v11.0.5
