name: Check for new ZMK releases

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *" # Run daily at 22:00 UTC

permissions:
  contents: write

jobs:
  upgrade-zmk:
    uses: urob/zmk-actions/.github/workflows/upgrade-zmk.yml@21d0254c00fa8e85b20089df82dc5e96d5029bd4 # v11.0.5
    secrets:
      # Name of PAT with write access to pull requests
      token: ${{ secrets.ZMK_ACTIONS_TOKEN }}
